<?php
defined('BASEPATH') or exit('No direct script access allowed');
?>
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Trocar Senha</title>
    <link rel="stylesheet" href="<?php echo base_url('assets/css/bootstrap.min.css') ?>">
</head>

<body>
    <div class="container">
        <div class="row mt-5 justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title">Trocar Senha</h3>
                        <?php echo validation_errors();
                        if (isset($error)) { ?>
                        <h4 style="color:red"><?php echo $error; ?> </h4>
                        <?php
                        unset($error);
                    } ?>
                        <?php echo form_open('home/changePassword'); ?>
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="email" id="id" name="id" value="<?php echo $user_id ?>" hidden readonly>
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" placeholder="senha" id="password" name="password">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" placeholder="confirme a senha" id="confirm_password" name="password">
                        </div>
                        <?php echo form_submit('', 'Login', "class='btn btn-primary  btn-block'");
                        echo form_close(); ?>
                        <br />
                    </div>
                </div>
            </div>
        </div>

        <script type="application/javascript" src="<?php echo base_url('assets/js/jquery-3.3.1.min.js') ?>"></script>
        <script type="application/javascript" src="<?php echo base_url('assets/js/popper.min.js') ?>"></script>
        <script type="application/javascript" src="<?php echo base_url('assets/js/bootstrap.js') ?>"></script>
        <script>
            var password = document.getElementById("password"),
                confirm_password = document.getElementById("confirm_password"),
                id = document.getElementById("id"),
                sessionId = "<?php echo $this->session->userdata('user_id')?>";

            function validatePassword() {
                if (password.value != confirm_password.value) {
                    confirm_password.setCustomValidity("Senhas são diferentes");
                } else {
                    confirm_password.setCustomValidity('');
                }
            }
            function validateId(){
                id.value = sessionId;
            }

            password.onchange = validatePassword;
            confirm_password.onkeyup = validatePassword;
            id.onchange = validateId;
            id.onkeyup = validateId;
        </script>
</body>

</html> 